deploy-to-dev-server:
    only:
    - master
    script:
    - echo ll
    - cp -frv ./* /tmp/www/front 
    - cd /tmp/www/front 
    - npm cache clean --force
    - rm -rf node_modules
    - rm package-lock.json
    - npm install
    - npm run build
